# Generated by Django 3.1.4 on 2020-12-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('married', models.BooleanField()),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('fav_actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.director')),
            ],
        ),
    ]
